/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { 
  Calendar, 
  FileText, 
  Sparkles, 
  Copy, 
  Check, 
  Download, 
  Trash2, 
  Info,
  Layers,
  AlertCircle
} from 'lucide-react';
import { MoMResult } from '../types';
import { generateMoM } from '../services/api';

interface MoMGeneratorViewProps {
  onAddActivity: (activity: any) => void;
  onIncrementMeetings: () => void;
  onAddActionItems: (count: number) => void;
}

// Sample transcript to enable easy evaluation out-of-the-box
const sampleTranscript = `Marcus: Alright crew. Let's align on the Q3 release schedule. We are targeting August 15th, but our core payment webhook processor is still experiencing high latency under simulated heavy traffic.

Sarah: Yes, I noticed SQL deadlock warnings occurring during multi-tenant registration lockups. I can diagnose this block and restructure our staging tables with more precise database indexes by Tuesday.

Nikolas: Sounds good, Sarah. Once you've restructured that, please commit the schema changes to the master repo. I will take care of drafting the automated schema migration runner script and execute dry-runs on the staging environment. Let's aim to have that staging trial fully live by Friday, August 18th.

Isabelle: Meanwhile, what is the status of our redesigned subscriber billing interface in Figma? Marcus?

Marcus: I'm finishing the high-fidelity animations for our upgraded billing widgets. The design aligns with the modern neutral gray palette. I'll pass the files to the frontend squad by Wednesday afternoon so that development can begin next sprint.

Sarah: Perfect. Let's recap: I'll clear deadlocks by Tuesday, Marcus delivers designs Wednesday, and Nikolas deploys staging schemas by Friday. Let's sync up again this Thursday.`;

export default function MoMGeneratorView({
  onAddActivity,
  onIncrementMeetings,
  onAddActionItems
}: MoMGeneratorViewProps) {
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [result, setResult] = useState<MoMResult | null>(null);
  const [copied, setCopied] = useState(false);

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm({
    defaultValues: {
      meetingName: 'Q3 Payment Pipeline Coordination & Sprint Alignment Sync',
      meetingDate: new Date().toISOString().split('T')[0],
      meetingNotes: sampleTranscript
    }
  });

  const notesText = watch('meetingNotes');

  const handleClear = () => {
    setValue('meetingNotes', '');
    setResult(null);
  };

  const handleLoadSample = () => {
    setValue('meetingNotes', sampleTranscript);
    setValue('meetingName', 'Q3 Payment Pipeline Coordination & Sprint Alignment Sync');
  };

  const onSubmit = async (data: any) => {
    setLoading(true);
    setErrorMsg(null);
    setResult(null);

    try {
      const gResult = await generateMoM(data.meetingName, data.meetingDate, data.meetingNotes);
      setResult(gResult);
      
      // Update core metrics and activity logs
      onIncrementMeetings();
      if (gResult.actionItems?.length > 0) {
        onAddActionItems(gResult.actionItems.length);
      }

      onAddActivity({
        id: `mom-${Date.now()}`,
        type: 'mom',
        title: data.meetingName,
        timestamp: new Date().toLocaleTimeString() + ' (UTC)',
        status: 'completed',
        details: `MoM processed successfully. Extracted ${gResult.actionItems.length} core action requirements.`
      });

    } catch (err: any) {
      setErrorMsg(err?.message || 'The AI generation server encountered a pipeline timeout.');
    } finally {
      setLoading(false);
    }
  };

  // Copy formatted MoM details to user's clipboard
  const handleCopyToClipboard = () => {
    if (!result) return;

    const formattedString = `MINUTES OF MEETING: ${watch('meetingName')}
Date: ${watch('meetingDate')}
Generated by AI PM Assistant

1. EXECUTIVE SUMMARY:
${result.meetingSummary}

2. THEMATIC DISCUSSION POINTS:
${result.discussionPoints.map((point, idx) => ` - ${point}`).join('\n')}

3. REQUISITE ACTION ITEMS:
${result.actionItems.map((item, idx) => ` [ ] Task: ${item.task} | Owner: ${item.assignee} | Due: ${item.dueDate} | Priority: ${item.priority}`).join('\n')}
`;

    navigator.clipboard.writeText(formattedString);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // MS Word styled HTML document downloader
  const handleDownloadDoc = () => {
    if (!result) return;

    const name = watch('meetingName');
    const date = watch('meetingDate');

    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <title>Minutes of Meeting - ${name}</title>
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #1e293b; padding: 40px; }
          h1 { color: #0f172a; border-bottom: 2px solid #2563eb; padding-bottom: 8px; font-size: 24px; }
          h2 { color: #1e3a8a; margin-top: 24px; font-size: 18px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px;}
          p, li { font-size: 14px; margin-bottom: 8px; }
          .meta { color: #64748b; font-size: 12px; margin-bottom: 20px; line-height: 1.4;}
          table { width: 100%; border-collapse: collapse; margin-top: 15px; }
          th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; font-size: 13px; }
          th { background-color: #f1f5f9; font-weight: bold; color: #0f172a; }
          .high { color: #b91c1c; font-weight: bold; }
          .medium { color: #b45309; font-weight: bold; }
          .low { color: #15803d; font-weight: bold; }
        </style>
      </head>
      <body>
        <h1>Minutes of Meeting (MoM)</h1>
        <div class="meta">
          <strong>Meeting:</strong> ${name}<br/>
          <strong>Date:</strong> ${date}<br/>
          <strong>Generated at:</strong> ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()} (UTC)<br/>
          <strong>Provider:</strong> Enterprise AI Project Manager Copilot
        </div>
        
        <h2>1. Executive Summary</h2>
        <p>${result.meetingSummary}</p>
        
        <h2>2. Discussion & Technical Points</h2>
        <ul>
          ${result.discussionPoints.map(point => `<li>${point}</li>`).join('')}
        </ul>
        
        <h2>3. Action Items Matrix</h2>
        <table>
          <thead>
            <tr>
              <th>Requisite Core Task Line</th>
              <th>Responsible Assignee</th>
              <th>Target Timeline</th>
              <th>Urgency Priority</th>
            </tr>
          </thead>
          <tbody>
            ${result.actionItems.map(item => `
              <tr>
                <td>${item.task}</td>
                <td>${item.assignee}</td>
                <td>${item.dueDate}</td>
                <td class="${item.priority.toLowerCase()}">${item.priority}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </body>
      </html>
    `;

    const blob = new Blob(['\ufeff' + htmlContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const tempLink = document.createElement('a');
    tempLink.href = url;
    tempLink.download = `${name.replace(/\s+/g, '_')}_MoM.doc`;
    document.body.appendChild(tempLink);
    tempLink.click();
    document.body.removeChild(tempLink);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Upper Pitch Grid Panel with Bold Typography */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-gray-200 dark:border-slate-800 pb-5">
        <div className="space-y-1">
          <h1 className="bold-header text-slate-900 dark:text-white">
            MoM Generator
          </h1>
          <p className="text-sm text-slate-500 dark:text-gray-400 font-semibold">
            Convert raw, unstructured chat streams or meeting transcript logs into fully indexed deliverables.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Input Form Column */}
        <div className="lg:col-span-5 space-y-4">
          <form onSubmit={handleSubmit(onSubmit)} className="bg-white dark:bg-[#111927] border border-gray-100 dark:border-gray-850 rounded-2xl p-6 shadow-sm space-y-4">
            
            {/* Header branding info */}
            <div className="flex items-center gap-2 text-xs font-semibold text-blue-600 dark:text-blue-400">
              <Layers className="w-4.5 h-4.5" />
              INPUT SPECIFICATION CORE
            </div>

            {/* Meeting Name Input */}
            <div className="space-y-1">
              <label htmlFor="meetingName" className="block text-xs font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                Meeting Title Name
              </label>
              <input
                id="meetingName"
                type="text"
                placeholder="Session identifier name"
                className={`w-full px-4 py-2.5 bg-gray-50 dark:bg-[#1f293d]/40 border ${
                  errors.meetingName ? 'border-red-400' : 'border-gray-205 dark:border-gray-800'
                } rounded-xl text-xs text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500`}
                {...register('meetingName', { required: 'Meeting Name is required to formulate artifacts.' })}
              />
              {errors.meetingName && (
                <p className="text-xs text-red-500 font-medium ml-1 mt-0.5">{errors.meetingName.message}</p>
              )}
            </div>

            {/* Meeting Date Input */}
            <div className="space-y-1">
              <label htmlFor="meetingDate" className="block text-xs font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                Meeting Date
              </label>
              <div className="relative">
                <input
                  id="meetingDate"
                  type="date"
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-[#1f293d]/40 border border-gray-205 dark:border-gray-800 rounded-xl text-xs text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                  {...register('meetingDate')}
                />
              </div>
            </div>

            {/* Large notes text area */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label htmlFor="meetingNotes" className="block text-xs font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                  Unstructured Meeting Notes / Transcript
                </label>
                <div className="flex gap-2.5">
                  <button
                    type="button"
                    onClick={handleLoadSample}
                    className="text-[10px] text-blue-600 dark:text-blue-400 hover:underline font-bold tracking-wide flex items-center gap-1 cursor-pointer"
                  >
                    <Info className="w-3 h-3" />
                    Load Sample Script
                  </button>
                  {notesText && (
                    <button
                      type="button"
                      onClick={handleClear}
                      className="text-[10px] text-red-550 dark:text-red-400 hover:underline font-bold tracking-wide flex items-center gap-1 cursor-pointer"
                    >
                      <Trash2 className="w-3 h-3" />
                      Clear Notes
                    </button>
                  )}
                </div>
              </div>
              <textarea
                id="meetingNotes"
                rows={12}
                placeholder="Paste direct transcripts, raw Slack sync dumps, bullet point notes, or audio conversion logs here..."
                className={`w-full px-4 py-3 bg-gray-50 dark:bg-[#1f293d]/40 border ${
                  errors.meetingNotes ? 'border-red-400' : 'border-gray-205 dark:border-gray-800'
                } rounded-2xl text-xs leading-relaxed text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono`}
                {...register('meetingNotes', { required: 'Please enter transcript or meeting notes text.' })}
              />
              <div className="flex justify-between items-center text-[10px] text-gray-400 dark:text-gray-500 font-medium px-1">
                <span>Supports natural conversational text</span>
                <span>{notesText ? notesText.length : 0} characters</span>
              </div>
              {errors.meetingNotes && (
                <p className="text-xs text-red-550 font-medium ml-1 mt-0.5">{errors.meetingNotes.message}</p>
              )}
            </div>

            {/* Action Buttons */}
            <button
              type="submit"
              disabled={loading}
              className="w-full flex items-center justify-center gap-2.5 px-5 py-3 bg-blue-600 hover:bg-blue-500 active:bg-blue-700 disabled:bg-blue-600/50 text-white font-medium text-xs rounded-xl cursor-pointer shadow-lg shadow-blue-500/10 transition-all duration-150"
            >
              {loading ? (
                <>
                  <svg className="animate-spin h-4.5 w-4.5 text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                  Processing Sync Transcripts...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  Synthesize MoM Document
                </>
              )}
            </button>

          </form>
        </div>

        {/* Output Section Column */}
        <div className="lg:col-span-7">
          
          {errorMsg && (
            <div className="p-4 bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-900 rounded-2xl flex items-start gap-3 text-xs mb-4">
              <AlertCircle className="w-5 h-5 text-red-500 mt-0.5 flex-shrink-0" />
              <div>
                <span className="font-bold text-red-800 dark:text-red-400 block mb-0.5">Synthesis Pipeline Failure</span>
                <p className="text-red-700 dark:text-red-400 font-medium leading-relaxed">{errorMsg}</p>
              </div>
            </div>
          )}

          {!result && !loading && (
            <div className="h-full bg-slate-50 dark:bg-[#111927]/30 border border-dashed border-slate-200 dark:border-slate-800 rounded-2xl flex flex-col items-center justify-center text-center p-8 min-h-[460px]">
              <div className="p-4 bg-white dark:bg-[#111927] border border-gray-100 dark:border-gray-800 rounded-full text-slate-400 mb-4 shadow-sm">
                <FileText className="w-8 h-8" />
              </div>
              <h3 className="font-display text-sm font-semibold text-gray-900 dark:text-slate-350">
                MoM Output Area
              </h3>
              <p className="text-xs text-gray-400 dark:text-gray-500 mt-1.5 max-w-sm leading-relaxed">
                Configure your meeting guidelines in the specification panel and click generate to trigger AI semantic synthesizers.
              </p>
            </div>
          )}

          {loading && (
            <div className="h-full bg-white dark:bg-[#111927] border border-gray-105 dark:border-gray-850 rounded-2xl flex flex-col items-center justify-center text-center p-8 min-h-[460px]">
              <div className="relative flex items-center justify-center mb-6">
                <div className="w-12 h-12 rounded-full border-4 border-blue-100 dark:border-blue-950/45 animate-pulse" />
                <div className="w-8 h-8 rounded-full border-3 border-blue-500 border-t-transparent animate-spin absolute" />
              </div>
              <h4 className="font-display text-sm font-semibold text-gray-850 dark:text-slate-300">
                AI Agent Summarization Active
              </h4>
              <p className="text-xs text-gray-450 dark:text-gray-500 mt-2 max-w-xs leading-normal">
                Structuring deliverables, determining assignee context groups, and filtering duplicate discussion notes in real-time.
              </p>
            </div>
          )}

          {result && !loading && (
            <div className="bg-white dark:bg-[#111927] border border-gray-105 dark:border-gray-850 rounded-2xl shadow-sm overflow-hidden animate-fade-in space-y-6 p-6">
              
              {/* Output Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-gray-100 dark:border-gray-800 pb-4">
                <div>
                  <h3 className="font-display text-base font-bold text-gray-900 dark:text-white">
                    Synthesized Minutes of Meeting
                  </h3>
                  <p className="text-[10px] text-gray-400 dark:text-gray-500 font-mono mt-0.5 uppercase tracking-wide">
                    Generated: {result.generatedAt} • Code: PM-MOM-EXTRACT
                  </p>
                </div>
                <div className="flex items-center gap-2 self-start sm:self-auto">
                  
                  {/* Copy Button */}
                  <button
                    type="button"
                    onClick={handleCopyToClipboard}
                    className="inline-flex items-center gap-1.5 px-3 py-2 text-xs bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-gray-700 hover:bg-gray-100 dark:hover:bg-slate-700 rounded-lg text-gray-700 dark:text-slate-350 font-bold transition-all cursor-pointer"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? 'Copied' : 'Copy'}
                  </button>

                  {/* Download DOCX */}
                  <button
                    type="button"
                    onClick={handleDownloadDoc}
                    className="inline-flex items-center gap-1.5 px-3 py-2 text-xs bg-blue-500 hover:bg-blue-600 text-white rounded-lg font-bold shadow-md shadow-blue-500/10 cursor-pointer transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download DOCX
                  </button>

                </div>
              </div>

              {/* Module 1: Meeting Summary */}
              <div className="space-y-2">
                <span className="block text-xs font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                  1. Executive Summary
                </span>
                <div className="p-4 bg-slate-50 dark:bg-[#1f293d]/20 border border-slate-100 dark:border-slate-800 rounded-xl text-xs leading-relaxed text-gray-750 dark:text-slate-300">
                  {result.meetingSummary}
                </div>
              </div>

              {/* Module 2: Key Discussion Points */}
              <div className="space-y-2.5">
                <span className="block text-xs font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                  2. Discussion Points & Alignments
                </span>
                <ul className="space-y-2 pl-3">
                  {result.discussionPoints.map((point, index) => (
                    <li key={index} className="text-xs leading-relaxed text-gray-750 dark:text-gray-300 flex items-start gap-2.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-2 flex-shrink-0" />
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Module 3: Action Items Table */}
              <div className="space-y-2.5 pt-2">
                <span className="block text-xs font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                  3. Action Items Matrix
                </span>
                
                {result.actionItems?.length === 0 ? (
                  <p className="text-xs text-gray-400 italic">No direct action items identified from transcript.</p>
                ) : (
                  <div className="border border-gray-100 dark:border-gray-800/80 rounded-xl overflow-hidden">
                    <div className="overflow-x-auto">
                      <table className="w-full text-left border-collapse text-xs">
                        <thead>
                          <tr className="bg-gray-50 dark:bg-gray-900/40 text-gray-400 text-[10px] font-bold uppercase tracking-wider border-b border-gray-100 dark:border-gray-800/60">
                            <th className="py-2.5 px-4">Action Task Description</th>
                            <th className="py-2.5 px-4 font-sans">Owner Assignee</th>
                            <th className="py-2.5 px-4">Timeline</th>
                            <th className="py-2.5 px-4 text-center">Priority</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100 dark:divide-gray-800 text-gray-750 dark:text-slate-300">
                          {result.actionItems.map((item, index) => (
                            <tr key={index} className="hover:bg-gray-50/50 dark:hover:bg-[#1f293d]/10">
                              <td className="py-3 px-4 font-medium leading-relaxed max-w-xs">{item.task}</td>
                              <td className="py-3 px-4 font-medium text-slate-500 dark:text-slate-400 whitespace-nowrap">{item.assignee}</td>
                              <td className="py-3 px-4 text-slate-400 whitespace-nowrap">{item.dueDate}</td>
                              <td className="py-3 px-4 text-center">
                                <span className={`inline-block px-2 py-0.5 rounded text-[9px] font-bold uppercase ${
                                  item.priority === 'High' ? 'bg-red-50 dark:bg-red-950/30 text-red-700 dark:text-red-400 border border-red-100 dark:border-red-900/30' :
                                  item.priority === 'Medium' ? 'bg-amber-50 dark:bg-amber-950/30 text-amber-700 dark:text-amber-400 border border-amber-100 dark:border-amber-900/30' :
                                  'bg-green-50 dark:bg-green-950/30 text-green-700 dark:text-green-400 border border-green-100 dark:border-green-900/30'
                                }`}>
                                  {item.priority}
                                </span>
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                )}
              </div>

            </div>
          )}

        </div>

      </div>

    </div>
  );
}
